# Generated by Django 5.0.2 on 2024-02-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sport_app", "0002_gender_maritalstatus_relationship_soccerposition_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screening",
            old_name="relationship",
            new_name="relationship_to_next_of_kin",
        ),
    ]
