# Generated by Django 5.0.2 on 2024-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sport_app", "0003_rename_relationship_screening_relationship_to_next_of_kin"),
    ]

    operations = [
        migrations.AddField(
            model_name="screening",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
